# Generated by Django 5.2 on 2025-05-05 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='metal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.metaltype', verbose_name='Тип Металла'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.size', verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation_key',
            field=models.CharField(blank=True, help_text='Уникальный ключ вариации товара', max_length=100),
        ),
    ]
